outputs:
 - template : "{{ .RootDir }}/{{ .Plugin.Type }}/README.tmpl"
   target: README.md
   processExisting: true
 - template : "{{ .RootDir }}/{{ .Plugin.Type }}/POLICY_STUDIO_DOC.tmpl"
   target: POLICY_STUDIO_DOC.md
chunks:
  - template: docs/overview.md
    required: true
  - template: docs/usage.md
  - template: "{{ .RootDir }}/errors.tmpl"
    type: table
    data:
      table: docs/errors.yaml
      columns:
        - key: Key
        - params: Parameters
  - template: "{{ .RootDir }}/matrix.tmpl"
    type: table
    required: true
    data:
      table: docs/matrix.yaml
      columns:
        - plugin: Plugin version
        - apim: APIM
        - am: AM
        - cockpit: Cockpit
        - comment: Comment
  - template: "{{ .RootDir }}/policy/phases.tmpl"
    type: table
    required: true
    data:
      table: docs/phases.yaml
      columns:
        - v2: v2 Phases
        - v2-comp: Compatible?
        - v4: v4 Phases
        - v4-comp: Compatible?
  - template: "{{ .RootDir }}/configuration_options.tmpl"
    type: options
    required: true
    data:
      schema: src/main/resources/schemas/schema-form.json
  - template: "{{ .RootDir }}/examples.tmpl"
    type: examples
    data:
      schema: src/main/resources/schemas/schema-form.json
      v4ApiPolicy: "{{ .RootDir }}/policy/api-v4-snippet.json.tmpl"
      v4ApiCRDPolicy: "{{ .RootDir }}/policy/crd-api-v4-snippet.yaml.tmpl"
    required: true
  - template: "{{ .RootDir }}/gateway_config.tmpl"
    type: code
    data:
      code: docs/gateway-config.yaml

