mainTemplate: "{{ .RMG_ROOT }}/{{ .Plugin.Type }}/dev_README.tmpl"
chunks:
  - template: "docs/overview.md"
    required: true
  - template: "{{ .RMG_ROOT }}/matrix.tmpl" # template to RMG_ROOT (built-in)
    type: table
    data:
      table: "docs/matrix.yaml"
    required: true
  - template: "docs/usage.md"
  - template: "{{ .RMG_ROOT }}/policy/phases.tmpl"
    data:
      table: "docs/phases.yaml"
    type: table
    required: true
#  - template: "{{ .RMG_ROOT }}/examples.md"
#    type: examples
#    data:
#      schemas:
#        - main: "src/main/resources/schemas/schema-form.json"
#    required: true
#  - template: "{{ .RMG_ROOT }}/configuration_options.md"
#    type: options
#    data:
#      schemas:
#        - main: "src/main/resources/schemas/schema-form.json"
  - template: "{{ .RMG_ROOT }}/gateway_config.tmpl"
    type: code
    data:
      code: "docs/gateway-config.yaml"
  - template: "{{ .RMG_ROOT }}/errors.tmpl"
    type: table
    data:
      table: "docs/errors.yaml"
