version: 2.1

orbs:
  gravitee: gravitee-io/gravitee@4.13.0
  go: circleci/go@3.0.2
  keeper: gravitee-io/keeper@0.7.0
  gh: circleci/github-cli@2.7.0
  azure-cli: circleci/azure-cli@1.3.2

parameters:
  go-version:
    type: string
    default: "1.23.1"
  trigger:
    type: enum
    default: none
    enum:
      - release
      - none

executors:
  azure-cli:
    docker:
      - image: mcr.microsoft.com/azure-cli:2.73.0
    resource_class: small

jobs:
  job-install-go-tools:
    docker:
      - image: cimg/go:<< pipeline.parameters.go-version >>-node
    steps:
      - checkout
      - go/load-mod-cache
      - run:
          name: Install GO tools
          command: make install-tools
      - go/save-mod-cache
      - save_cache:
          key: gotools-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/project/bin
  job-lint-sources:
    docker:
      - image: cimg/go:<< pipeline.parameters.go-version >>-node
    steps:
      - checkout
      - go/load-golangci-lint-cache
      - restore_cache:
          keys:
            - gotools-{{ checksum "go.sum" }}
      - run:
          name: Lint sources
          command: make lint-sources
      - go/save-golangci-lint-cache

  job-lint-commits:
    docker:
      - image: cimg/go:<< pipeline.parameters.go-version >>-node
    steps:
      - checkout
      - run:
          name: Install commitlint
          command: npm i @commitlint/config-conventional @commitlint/cli
      - run:
          name: Lint commits
          command: |
            node_modules/.bin/commitlint \
              -x @commitlint/config-conventional \
              --from $(git describe --tags --abbrev=0)

  job-unit-test:
    docker:
      - image: cimg/go:<< pipeline.parameters.go-version >>-node
    steps:
      - checkout
      - go/load-mod-cache
      - restore_cache:
          keys:
            - gotools-{{ checksum "go.sum" }}
      - run:
          name: Run unit tests
          command: |
            TEST_ARGS="--cover --coverprofile=cover-unit.out --coverpkg=github.com/gravitee-io/gravitee-doc-gen/... --output-dir=/tmp/junit/reports" \
             make -s test
      - go/save-mod-cache
  job-build-docker-image:
    docker:
      - image: cimg/go:<< pipeline.parameters.go-version >>-node
    parameters:
      image:
        type: string
      tag:
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - gravitee/docker-login:
          registry: graviteeio.azurecr.io
          username: keeper://Q721P2LSOPJ9qiXLuf5AHQ/field/login
          password: keeper://Q721P2LSOPJ9qiXLuf5AHQ/field/password
      - run:
          name: Build image << parameters.image >>
          command: IMG=<< parameters.image >> TAG=<< parameters.tag >> make docker-build
      - run:
          name: Push image << parameters.image >>:<<parameters.tag >>
          command: |
            IMG=<< parameters.image >> TAG=<< parameters.tag >> make docker-push
      - gravitee/docker-logout:
          registry: graviteeio.azurecr.io

workflows:
  pull-request:
    jobs:
      - job-install-go-tools:
          name: Install GO tools
      - job-lint-sources:
          name: Lint sources
          requires:
            - Install GO tools
      - job-lint-commits:
          name: Lint commits
          requires:
            - Install GO tools
      - job-unit-test:
          name: Run unit tests
          requires:
            - Install GO tools
      - job-build-docker-image:
          name: Dev image
          requires:
            - Lint sources
            - Lint commits
            - Run unit tests
          image: graviteeio.azurecr.io/doc-gen
          tag: dev-<<pipeline.git.revision>>
          context: cicd-orchestrator
          filters:
            tags:
              ignore: /.*/
  post-merge:
    when:
      equal:
        - none
        - << pipeline.parameters.trigger >>
    jobs:
      - job-build-docker-image:
          name: Prod image
          image: graviteeio.azurecr.io/doc-gen
          tag: latest
          context: cicd-orchestrator
          filters:
            branches:
              only:
                - /^[0-9]+\.[0-9]+\.x$/
                - main
            tags:
              ignore: /.*/