version: 2.1

orbs:
  gravitee: gravitee-io/gravitee@5.1.1
  go: circleci/go@3.0.2
  keeper: gravitee-io/keeper@0.7.0
  gh: circleci/github-cli@2.7.0
  azure-cli: circleci/azure-cli@1.3.2

parameters:
  go-version:
    type: string
    default: "1.23.1"

executors:
  azure-cli:
    docker:
      - image: mcr.microsoft.com/azure-cli:2.73.0
    resource_class: small

jobs:
  job-install-go-tools:
    docker:
      - image: cimg/go:<< pipeline.parameters.go-version >>-node
    steps:
      - checkout
      - go/load-mod-cache
      - run:
          name: Install GO tools
          command: make install-tools
      - go/save-mod-cache
      - save_cache:
          key: gotools-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/project/bin
  job-lint-sources:
    docker:
      - image: cimg/go:<< pipeline.parameters.go-version >>-node
    steps:
      - checkout
      - go/load-golangci-lint-cache
      - restore_cache:
          keys:
            - gotools-{{ checksum "go.sum" }}
      - run:
          name: Lint sources
          command: make lint-sources
      - go/save-golangci-lint-cache
  job-lint-licenses:
    docker:
      - image: cimg/go:<< pipeline.parameters.go-version >>-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - gotools-{{ checksum "go.sum" }}
      - run:
          name: Lint licenses
          command: make lint-licenses
  job-lint-commits:
    docker:
      - image: cimg/go:<< pipeline.parameters.go-version >>-node
    steps:
      - checkout
      - run:
          name: Install commitlint
          command: npm i @commitlint/config-conventional @commitlint/cli
      - run:
          name: Lint commits
          command: |
            node_modules/.bin/commitlint \
              -x @commitlint/config-conventional \
              --from $(git describe --tags --abbrev=0)

  job-unit-test:
    docker:
      - image: cimg/go:<< pipeline.parameters.go-version >>-node
    steps:
      - checkout
      - go/load-mod-cache
      - restore_cache:
          keys:
            - gotools-{{ checksum "go.sum" }}
      - run:
          name: Run unit tests
          command: |
            TEST_ARGS="--cover --coverprofile=cover-unit.out --coverpkg=github.com/gravitee-io/gravitee-doc-gen/... --output-dir=/tmp/junit/reports" \
             make -s test
      - go/save-mod-cache

  release:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Build the binary using make
          command: GOOS=linux GOARCH=amd64 make build
      - run:
          name: Get latest commit message
          command: |
            git log -1 --pretty=%B > release-notes.txt
      - keeper/env-export:
          secret-url: keeper://TIlcGPFq4rN5GvgnZb9hng/field/password
          var-name: GITHUB_TOKEN
      - gh/setup
      - run:
          name: Create GitHub Release and Upload Asset
          command: |
            gh release create "<< pipeline.git.tag >>" ./bin/doc-gen \
              --title "<< pipeline.git.tag >>" \
              --notes-file release-notes.txt \
              --clobber

workflows:
  pull-request:
    jobs:
      - job-install-go-tools:
          name: Install GO tools
          filters:
            branches:
              ignore:
                - /^[0-9]+\.[0-9]+\.x$/
                - main
            tags:
              ignore: /.*/
      - job-lint-sources:
          name: Lint sources
          requires:
            - Install GO tools
      - job-lint-commits:
          name: Lint commits
          requires:
            - Install GO tools
      - job-lint-licenses:
          name: Lint licenses
          requires:
            - Install GO tools
      - job-unit-test:
          name: Run unit tests
          requires:
            - Install GO tools
      - gravitee/common_docker_build:
          name: Dev image
          context: cicd-orchestrator
          requires:
            - Lint sources
            - Lint commits
            - Lint licenses
            - Run unit tests
          dockerImage: doc-gen
          dockerTag: dev-<<pipeline.git.revision>>
          registry: graviteeio.azurecr.io
          username: keeper://Q721P2LSOPJ9qiXLuf5AHQ/field/login
          password: keeper://Q721P2LSOPJ9qiXLuf5AHQ/field/password

  post-merge:
    jobs:
      - gravitee/common_docker_build:
          context: cicd-orchestrator
          name: Main image
          dockerImage: doc-gen
          dockerTag: main
          registry: graviteeio.azurecr.io
          username: keeper://Q721P2LSOPJ9qiXLuf5AHQ/field/login
          password: keeper://Q721P2LSOPJ9qiXLuf5AHQ/field/password
          filters:
            branches:
              only:
                - main
            tags:
              ignore: /.*/
  tag-release:
    jobs:
      - release:
          context: cicd-orchestrator
          name: Release
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
      - gravitee/common_docker_build:
          context: cicd-orchestrator
          name: Prod image latest
          requires:
            - Release
          dockerImage: doc-gen
          dockerTag: latest
          registry: graviteeio
          username: keeper://cooU9UoXIk8Kj0hsP2rkBw/field/login
          password: keeper://cooU9UoXIk8Kj0hsP2rkBw/field/password
      - gravitee/common_docker_build:
          context: cicd-orchestrator
          name: Prod image << pipeline.git.tag >>
          requires:
            - Release
          dockerImage: doc-gen
          dockerTag: << pipeline.git.tag >>
          registry: graviteeio
          username: keeper://cooU9UoXIk8Kj0hsP2rkBw/field/login
          password: keeper://cooU9UoXIk8Kj0hsP2rkBw/field/password
